const products = [
  {
    id: 1,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Paracetamol 500mg',
    price: 55,
    qty: 0,
    description: 'Relieves fever and mild pain.',
  },
  {
    id: 2,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Dolo 650',
    price: 68,
    qty: 0,
    description: 'Effective for fever and body pain.',
  },
  {
    id: 3,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Crocin Advance',
    price: 62,
    qty: 0,
    description: 'Fast relief from fever and headache.',
  },
  {
    id: 4,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Azithromycin 500mg',
    price: 180,
    qty: 0,
    description: 'Antibiotic for bacterial infections.',
  },
  {
    id: 5,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Amoxicillin 500mg',
    price: 145,
    qty: 0,
    description: 'Treats bacterial infections.',
  },
  {
    id: 6,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Cetirizine 10mg',
    price: 42,
    qty: 0,
    description: 'Relieves allergy symptoms.',
  },
  {
    id: 7,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Pantoprazole 40mg',
    price: 120,
    qty: 0,
    description: 'Reduces stomach acid and acidity.',
  },
  {
    id: 8,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Omeprazole 20mg',
    price: 98,
    qty: 0,
    description: 'Treats acid reflux and ulcers.',
  },
  {
    id: 9,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Metformin 500mg',
    price: 135,
    qty: 0,
    description: 'Controls blood sugar levels.',
  },
  {
    id: 10,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Glimepiride 2mg',
    price: 160,
    qty: 0,
    description: 'Used for type 2 diabetes.',
  },
  {
    id: 11,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Amlodipine 5mg',
    price: 85,
    qty: 0,
    description: 'Helps control high blood pressure.',
  },
  {
    id: 12,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Telmisartan 40mg',
    price: 210,
    qty: 0,
    description: 'Lowers blood pressure.',
  },
  {
    id: 13,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Atorvastatin 10mg',
    price: 175,
    qty: 0,
    description: 'Reduces bad cholesterol levels.',
  },
  {
    id: 14,
    category_id: 2,
    image: require('../images/medicine.jpg'),
    name: 'Ibuprofen 400mg',
    price: 75,
    qty: 0,
    description: 'Relieves pain and inflammation.',
  },
  {
    id: 15,
    category_id: 3,
    image: require('../images/medicine.jpg'),
    name: 'Diclofenac 50mg',
    price: 95,
    qty: 0,
    description: 'Treats muscle and joint pain.',
  },
  {
    id: 16,
    category_id: 3,
    image: require('../images/medicine.jpg'),
    name: 'Ondansetron 4mg',
    price: 110,
    qty: 0,
    description: 'Prevents nausea and vomiting.',
  },
  {
    id: 17,
    category_id: 3,
    image: require('../images/medicine.jpg'),
    name: 'Vitamin C Tablets',
    price: 150,
    qty: 0,
    description: 'Supports immunity and health.',
  },
  {
    id: 18,
    category_id: 3,
    image: require('../images/medicine.jpg'),
    name: 'Calcium Tablets',
    price: 185,
    qty: 0,
    description: 'Strengthens bones and teeth.',
  },
  {
    id: 19,
    category_id: 4,
    image: require('../images/medicine.jpg'),
    name: 'Cough Syrup',
    price: 125,
    qty: 0,
    description: 'Provides relief from dry cough.',
  },
  {
    id: 20,
    category_id: 4,
    image: require('../images/medicine.jpg'),
    name: 'Antacid Syrup',
    price: 105,
    qty: 0,
    description: 'Relieves acidity and indigestion.',
  },
];

export default products;
